version: '3.9'

services:
  db:
    image: postgres:15
    container_name: atybank-postgres
    environment:
      POSTGRES_USER: atybank
      POSTGRES_PASSWORD: atybank123
      POSTGRES_DB: atybank
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atybank"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
